# Generated by Django 5.0.6 on 2024-07-08 13:19

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='article',
            field=models.CharField(default=goods.models.generate_article, max_length=10),
        ),
    ]
