# Generated by Django 5.0.6 on 2024-07-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='article',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Уникальный номер посылки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.type', verbose_name='Тип посылки'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=52, verbose_name='Название'),
        ),
    ]
