# Generated by Django 5.0.6 on 2024-07-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_package_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
